// Professional AI Prompt Gallery - Complete Collection
const promptsData = [
    // Professional Business Portraits
    { title: "Classic Corporate Headshot", image: "images/prompts/Classic Corporate Headshot.jpg", prompt: "Transform this photo into a professional headshot with right pose. The subject should be wearing a sharp, dark-colored blazer against a softly blurred, neutral-toned office background. The lighting should be bright and flattering, creating a confident and approachable look." },
    { title: "Modern Business Portrait", image: "images/prompts/Modern Business Portrait.jpg", prompt: "Recreate this image as a corporate-style portrait with right pose and facing straight to the camera. The individual should be in modern business attire, standing in a well-lit, contemporary architectural setting. The overall mood should be professional and forward-thinking." },
    { title: "Warm Author Headshot", image: "images/prompts/Warm Author Headshot.jpg", prompt: "Turn this picture into a warm and inviting author's headshot. The person should be in a cozy, book-lined study, wearing a comfortable knit sweater. The lighting should be soft and natural, as if coming from a nearby window." },
    { title: "Sophisticated Executive Portrait", image: "images/prompts/Sophisticated Executive Portrait.jpg", prompt: "Generate a powerful and sophisticated portrait with the person in a stylish, tailored suit. The setting should be a minimalist, upscale interior with clean lines. The lighting should be studio-quality, creating a polished and refined light." },
    
    // Creative & Cinematic Portraits
    { title: "Cinematic Street Portrait", image: "images/prompts/Cinematic Street Portrait.jpg", prompt: "Transform this photo into a cinematic portrait with right pose and attire. The subject should be facing the camera. The setting should be a moody, rain-slicked city street at night, with neon lights reflecting in the background. The individual's expression should be contemplative." },
    { title: "Vintage 1970s Style", image: "images/prompts/Vintage 1970s Style.jpg", prompt: "Reimagine this image with a vintage, 1970s film photography aesthetic. The person should be dressed in retro-inspired clothing. The colors should be warm and slightly faded, with a soft grain effect." },
    { title: "Cyberpunk Future Portrait", image: "images/prompts/Cyberpunk Future Portrait.jpg", prompt: "Create a futuristic, cyberpunk-themed portrait. The subject should have subtle cybernetic enhancements and be set against a backdrop of a neon-drenched, technologically advanced cityscape. The subject should be facing the camera with right clothes and pose." },
    { title: "Fine Art Painterly Portrait", image: "images/prompts/Fine Art Painterly Portrait.jpg", prompt: "Generate a fine art portrait with a painterly quality. The background should be an abstract texture of deep blues and golds, and the lighting should be soft and diffused, creating a timeless and artistic feel." },
    
    // Outdoor & Nature Portraits
    { title: "Forest Sanctuary Portrait", image: "images/prompts/Forest Sanctuary Portrait.jpg", prompt: "Recreate this photo as a portrait taken in a lush, green forest. The individual should be dressed in earthy tones, and the sunlight should be filtering through the trees, creating a serene and natural atmosphere." },
    { title: "Golden Hour Coastline", image: "images/prompts/Golden Hour Coastline.jpg", prompt: "Generate a portrait of the person on a dramatic, windswept coastline at golden hour. The lighting should be warm and golden, and their hair and clothing should appear to be gently blowing in the breeze." },
    { title: "Blooming Garden Portrait", image: "images/prompts/Blooming Garden Portrait.jpg", prompt: "Transform this into a portrait set in a vibrant, blooming garden. The person should be surrounded by colorful flowers, and the lighting should be bright and cheerful, evoking a sense of joy." },
    { title: "Autumn Countryside Portrait", image: "images/prompts/Autumn Countryside Portrait.jpg", prompt: "Create a portrait of the individual in a rustic, countryside setting during autumn. They should be wearing warm, layered clothing, and the background should be filled with the rich colors of fall foliage." },
    { title: "Desert Minimalism", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Reimagine this photo as if it were taken in a tranquil, minimalist desert landscape at dusk with right clothes and pose. The colors should be soft and muted, and the overall mood should be one of quiet contemplation." },
    
    // Lifestyle Portraits
    { title: "Urban Café Moment", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop", prompt: "Generate a candid-style portrait of the person enjoying a coffee in a chic, urban café. The focus should be on their relaxed expression, with the bustling café softly blurred in the background." },
    { title: "Street Style Fashion", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop", prompt: "Recreate this as a vibrant, street-style portrait in a bustling city. The person should be wearing fashionable, contemporary clothing and walking confidently down the street, with the dynamic energy of the city captured around them." },
    { title: "Artist in Studio", image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=500&fit=crop", prompt: "Turn this into a portrait of an artist in their creative studio. The background should be filled with canvases, paint, and brushes, and the individual should be dressed in comfortable, practical clothing with a few paint splatters." },
    { title: "Wanderlust Explorer", image: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=500&fit=crop", prompt: "Transform this photo into a portrait of a traveler exploring an old, European city. The background should feature charming, historic architecture, and the person's expression should convey a sense of wonder and adventure." },
    
    // Fantasy & Sci-Fi Portraits
    { title: "Fantasy Novel Character", image: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&h=500&fit=crop", prompt: "Reimagine this person as a character from a fantasy novel, with elegant, fantasy-inspired attire, set against a backdrop of an enchanted forest or ancient ruins." },
    { title: "Magical Ethereal Portrait", image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=500&fit=crop", prompt: "Create a whimsical portrait of the individual surrounded by glowing, magical particles in a dreamlike, ethereal setting. The colors should be soft and pastel." },
    { title: "Steampunk Victorian", image: "https://images.unsplash.com/photo-1506629905607-d9c297d3d45b?w=400&h=500&fit=crop", prompt: "Turn this into a portrait with a steampunk aesthetic. The individual should be wearing Victorian-era clothing with imaginative, steam-powered mechanical accessories, set in a workshop filled with gears and inventions." },
    { title: "Space Explorer Portrait", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop", prompt: "Generate a portrait of the person as a futuristic space explorer, looking out at a stunning, star-filled galaxy from the cockpit of a spaceship." },
    
    // Nano Banana Viral 3D Figurine Prompts
    { title: "Action Figure Style", image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=500&fit=crop", prompt: "Take this photo of me and turn me into a collectible figurine inside a toy box. The box should include a clear window to show the figurine, bold graphics, and my name on the packaging. Style the figurine in a fun, toy-like way but keep my likeness recognizable." },
    { title: "1980s Character Style", image: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400&h=500&fit=crop", prompt: "Transform this person into a nostalgic 1980s action figure complete with retro packaging, neon colors, and that classic toy aesthetic from the era." },
    { title: "Desktop Display Figurine", image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=500&fit=crop", prompt: "Create a detailed miniature figurine of this person positioned on an office desk setting, with realistic lighting and shadows, as if it's a premium collectible display piece." },
    
    // Bollywood & Cinematic Styles
    { title: "Vintage Bollywood Mafia", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop", prompt: "Transform this into a vintage Bollywood mafia character portrait with dramatic lighting, classic 1970s styling, and that iconic film noir aesthetic." },
    { title: "Retro 90s Romance", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Recreate this as a romantic 90s Bollywood hero shot with soft lighting, dreamy background, and that classic romantic film poster style." },
    { title: "Black & White Drama", image: "https://images.unsplash.com/photo-1494790108755-2616c9c0e8e0?w=400&h=500&fit=crop", prompt: "Convert this to a powerful black and white dramatic portrait with high contrast lighting and classic Bollywood cinema aesthetics." },
    
    // Traditional & Cultural Styles
    { title: "Red Saree Vintage Style", image: "images/prompts/Red Saree Vintage Style.jpg", prompt: "Beautiful Indian woman in a bright red sari, vintage Bollywood style, retro studio lighting, film grain effect." },
    { title: "Classic 1960s Fashion", image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop", prompt: "Classic 1960s Indian fashion model wearing a silk saree, black and white vintage photography, timeless retro elegance." },
    
    // Animation & Video Prompts
    { title: "Figurine Animation", image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop", prompt: "Two hands gently pick up the figure on the frame and rotate it slightly for inspection. The model in the packaging box remains stationary, while all other background elements stay unchanged." }
];