// Professional AI Prompt Gallery - Complete Collection
const promptsData = [
    // 3D Figurine Prompts
    { title: "Official Google Gemini 3D Figurine", image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=500&fit=crop", prompt: "Create a 1/7 scale commercialized figurine of the characters in the picture, in a realistic style, in a real environment. The figurine is placed on a computer desk. The figurine has a round transparent acrylic base, with no text on the base. Next to the computer is a toy packaging box, designed in a style reminiscent of high-quality collectible figures, printed with original artwork." },
    { title: "Action Figure Toy Box", image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=500&fit=crop", prompt: "Take this photo of me and turn me into a collectible figurine inside a toy box. The box should include a clear window to show the figurine, bold graphics, and my name on the packaging. Style the figurine in a fun, toy-like way but keep my likeness recognizable." },
    { title: "Biopunk Cyber Figurine", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop", prompt: "Transform this person into a biopunk figurine where technology and biology have merged. Their 'armor' is a semi-translucent, bioluminescent exoskeleton that pulses with a soft, glowing pattern of banana leaves in electric blue and magenta. Their cybernetic enhancements appear grown rather than built, with glowing veins visible beneath their skin. The background is a futuristic cityscape where bio-engineered flora intertwines with skyscrapers, and massive, glowing banana plants serve as streetlights. The air is thick with neon rain, creating an ethereal, glowing aura around the figure." },
    { title: "Feywild Enchanter Figurine", image: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&h=500&fit=crop", prompt: "Reimagine this person as a Feywild Enchanter figurine, as if they are one with nature. Their robes appear to be made of woven leaves and petals, with subtle golden banana patterns integrated into the fabric. They hold a staff of gnarled, glowing wood that has naturally grown into the shape of a banana, emitting magical pollen-like sparkles. A crown of intertwined, glowing vines forming a banana shape rests above their head. Set them in a whimsical, enchanted grove where the air is thick with a shimmering, magical mist and the flora glows with a soft, bioluminescent light." },
    { title: "Chibi Style Figurine", image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=500&fit=crop", prompt: "Transform this person into a sweet, dessert-themed chibi figurine. Design them with an oversized head, a small body, and an exaggeratedly cute expression. Their shoes should look like they're made from peeled bananas, and their cheeks should be a soft, rosy pink. Place them in a scene filled with floating, candy-coated mini-bananas, edible glitter, and rainbow sprinkles. The textures should be soft and almost edible, with a playful, sugar-like finish." },
    { title: "Pastel Kawaii Figurine", image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=500&fit=crop", prompt: "Generate a hyper-kawaii 3D figurine of this person with a distinct pastel-core aesthetic. The setting is mid-air, surrounded by a swirl of cotton candy clouds and glitter-filled, translucent banana balloons. Clothe the figure in a vibrant pastel gradient outfit accessorized with glowing banana jewelry. The lighting should be bright and magical, giving everything an iridescent sheen for a whimsical and eye-catching look." },
    { title: "Retro Pixel Art Style", image: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400&h=500&fit=crop", prompt: "Transform this person into a bold pixel art character from a classic arcade game, designed to attract players. The sprite should have vibrant outlines and be posed heroically on a Tron-like neon grid floor. They wield a glowing neon banana sword and a translucent pixel shield. The background is a dark space filled with flashing pixel stars and a high-score table. Add subtle horizontal scan lines across the entire image to perfectly capture the look of an authentic 80s coin-op arcade monitor." },
    { title: "Pop Art Comic Style", image: "https://images.unsplash.com/photo-1494790108755-2616c9c0e8e0?w=400&h=500&fit=crop", prompt: "Transform this person into a figurine straight from a vintage Sunday comic strip, rendered in a playful pop art style. Use thick, uniform black outlines and flat, bright colors like canary yellow, bubblegum pink, and sky blue, with some intentional off-register color bleed. The shading should be simple, using minimal halftone patterns. Their outfit is decorated with a fun, repeating banana print. A classic, rounded speech bubble above their head should read 'BANANA POWER!' in a fun, retro font. The background is a simple but impactful 'KAPOW!'-style burst with radiating action lines." },
    { title: "Anime Hero Figurine", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop", prompt: "Illustrate this person as a legendary warrior from a space fantasy anime, captured in a heroic splash-page pose. They are armed with the 'Celestial Banana Blade,' a sword glowing with immense power. Their design includes gravity-defying neon hair and intense, oversized manga eyes that radiate energy. Their outfit is a set of stylized, battle-worn armor with a dramatically flowing cloak, caught in a cosmic wind. Frame them against a backdrop of a swirling purple and blue nebula, with streaks of light suggesting faster-than-light travel. The overall style should be high-energy, with bold outlines and a powerful, mythic atmosphere." },
    
    // Bollywood & Retro Transformation Prompts
    { title: "1970s Bollywood Superstar (Women)", image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop", prompt: "Create a full-length photorealistic image of the uploaded person as a 1970s Bollywood superstar. Scene: outside a Mumbai cinema hall during a film premiere, marquee glowing in neon, vintage Bollywood posters on the walls. The subject is styled in Western-inspired Bollywood glamour of the 1970s, a shimmering sequined evening gown or satin jumpsuit with flared bottoms, a feather boa or faux fur stole draped over the shoulders, and platform heels. Accessories include oversized tinted sunglasses, chunky jewellery, and a clutch bag. Hair styled in voluminous waves or a glamorous blow-dry, with bold eyeliner and glossy lipstick completing the look. Surround them with flashing cameras, paparazzi holding vintage film cameras, and a crowd of fans reaching out for autographs. Add authentic 1970s colour grading (warm tones, film grain, cinematic contrast). Capture the aura of a confident, glamorous star making a grand entrance – charismatic, stylish, and larger-than-life." },
    { title: "1970s Bollywood Hero (Men)", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop", prompt: "Create a full-length photorealistic image of the uploaded person as a 1970s Bollywood superstar. Scene: outside a Mumbai cinema hall during a film premiere, with neon lights marquee, and vintage Bollywood posters on the walls. Style the subject in classic 70s hero fashion — a sharply tailored wide-collared suit with flared trousers, or a silk shirt left slightly unbuttoned paired with a patterned blazer, leather belt, and polished shoes. Accessories include aviator sunglasses, a silk scarf draped casually, or a gold chain for added flair. Hair styled in the signature retro look — side-parted, voluminous, or wavy — with a confident, expressive moustache if desired. Surround the subject with paparazzi holding vintage film cameras, bright flashbulbs, and enthusiastic fans reaching for autographs. Apply warm Eastmancolor tones, soft contrast, visible grain, and dramatic star lighting. Pose the subject mid-stride on the red carpet, waving with effortless charm, radiating the aura of a Bollywood superstar." },
    { title: "Golden Hour Studio Portrait", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Craft a moody studio portrait of the uploaded person bathed in a golden-orange spotlight that creates a glowing circular halo behind them on the wall. The warm light should sculpt the face and upper body with soft, sunset-like tones while casting a strong head shadow to the right. Style the person in classic attire with dramatic lighting." },
    { title: "Vintage Saree Portrait (Ultra Realistic)", image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop", prompt: "Make a 4K HD, realistic, and stunning portrait using this image. Show long, dark, wavy hair cascading over shoulders. Attire – a translucent, elegant black saree draped over one shoulder, revealing a fitted blouse underneath. White flowers are tucked behind her right ear. She is looking slightly to her right, with a soft, serene expression. The background is a plain, warm-toned wall, illuminated by a warm light source from the right, creating a distinct, soft-edged shadow of her profile and hair on the wall behind her. The overall mood is retro and artistic." },
    { title: "90s Movie Aesthetic", image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop", prompt: "Create a retro, vintage, grainy but bright image of the reference picture, but draped in a perfect beige-colour, Pinterest-y aesthetic retro saree. It must feel like a 90s movie, brown hair, baddie with a small flower tucked visibly into her wavy hair, and a romantic, windy environment. The girl is standing against a solid wall, deep shadows and contrast drama, creating a mysterious and artistic atmosphere where the lighting is warm with the golden tones of evoking a sunset or golden hour glow. The background is minimalist and slightly textured; the expression on her face is moody, calm, yet happy and introspective." },
    { title: "Cinematic Night Portrait (Paris)", image: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=500&fit=crop", prompt: "Create an ultra-realistic night-time portrait from this photo, standing near the Arc de Triomphe at Place Charles de Gaulle in Paris. Background: The Arc de Triomphe is fully visible and brightly illuminated in the center of the frame, with deep shadows and warm street lights glowing softly in the background. The classic 'Place Charles de Gaulle' street sign is clearly visible on the ornate lamppost to the right side of the subject. Lighting & Color: Maintain the warm, ambient nighttime lighting with subtle yellow-orange glows from the streetlights. Capture the same soft shadows and realistic noise/grain present in the original image. Apply similar color grading – warm highlights, deep shadows, and slightly muted tones to evoke a cinematic, moody feel. Pose & Angle: The subject is facing left, head tilted upward at a ~45-degree angle, with eyes closed and a serene, introspective expression." },
    { title: "Dramatic Black & White", image: "https://images.unsplash.com/photo-1494790108755-2616c9c0e8e0?w=400&h=500&fit=crop", prompt: "Make an epic black and white close-up portrait of the uploaded pic with wet hair and water droplets on my face and shoulders. Strong dramatic lighting, sharp facial features, glossy lips, piercing eyes, and realistic skin texture. High contrast, studio shot, hyper-realistic, cinematic look, 4K detail using this picture." },
    { title: "1970s Jazz Club Retro", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Create a hyper-realistic portrait of the uploaded person (preserve face 100%) styled as a 1970s retro icon. He is seated casually in a dimly lit lounge with vintage vinyl records stacked behind him, a glowing jukebox casting warm neon light across the scene. Outfit: open-collared patterned silk shirt, flared trousers, gold chain, and tinted aviator sunglasses. The lighting is warm amber with subtle film grain, evoking the ambience of old Bollywood jazz clubs. Pose is relaxed, with one arm resting on a velvet sofa and a confident half-smile." },
    { title: "Dark Aesthetic Portrait", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop", prompt: "Create a hyper-realistic, editorial-style portrait of the man in the image with a dark, alluring aesthetic. He has tousled, slightly wavy black hair that falls over his forehead, framing his face. His expression is serious and intense, with dark, soulful eyes. He wears a sleek black suit over a deep red, partially unbuttoned dress shirt that reveals an intricate, full chest and neck tattoo featuring symmetrical, detailed designs and a web motif at the center of his throat. A single long, gold earring dangles from one ear. A vivid red rose is pinned to the lapel of his suit jacket, enhancing the romantic and dramatic tone of the portrait." },
    { title: "High Fashion LV Style", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop", prompt: "Make a hyper-realistic portrait of the uploaded person (preserve face 100%) wearing a high-end fashion LV outfit. The background is orange, the clothing is minimal, as a hyper-realistic scene, the guy is just slightly visible due to dark shadows, and he is wearing modern fashion frames." },
    { title: "Golden Hour Window Light", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Create a softly lit portrait of the uploaded person standing indoors near a window with warm sunlight streaming through. Use a cinematic, golden-hour lighting style that highlights the face and hair with natural glow and soft shadows. The person should be wearing a loose, casual white shirt with slightly rolled-up sleeves. The mood should feel calm, dreamy, and natural, with soft depth of field and a warm, intimate atmosphere." },
    { title: "Relaxed Authority Pose", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop", prompt: "A hyper-realistic cinematic editorial portrait of the uploaded person (preserve face 100%). He stands tall in a dark, moody studio, surrounded by soft, drifting smoke under a dramatic spotlight. Outfit: Oversized slate-blue luxury suit with wide-leg trousers, paired with a slightly unbuttoned white silk shirt. Both hands tucked casually in pockets, shoulders relaxed, confident expression, head tilted slightly upward." },
    { title: "Cinematic Dramatic Saree", image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop", prompt: "Generate a cinematic, hyper-realistic photo of the uploaded person wearing a flowing, deep-purple silk saree against a dramatic, stormy sky at dusk. The saree is billowing in the wind. The lighting is moody and high-contrast, with a single light source from the left highlighting the folds of the fabric and casting a long, dramatic shadow. The expression is intense and focused, as if a scene from a movie." },
    
    // Environment Transformation Prompts
    { title: "Tropical House Makeover", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Transform this house into a vibrant tropical island design. Replace the roof with thatch and add bamboo structural elements. Surround it with lush, colorful tropical plants and palm trees." },
    
    // Professional Business Portraits
    { title: "Classic Corporate Headshot", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Transform this photo into a professional headshot with right pose. The subject should be wearing a sharp, dark-colored blazer against a softly blurred, neutral-toned office background. The lighting should be bright and flattering, creating a confident and approachable look." },
    { title: "Modern Business Portrait", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop", prompt: "Recreate this image as a corporate-style portrait with right pose and facing straight to the camera. The individual should be in modern business attire, standing in a well-lit, contemporary architectural setting. The overall mood should be professional and forward-thinking." },
    { title: "Warm Author Headshot", image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=500&fit=crop", prompt: "Turn this picture into a warm and inviting author's headshot. The person should be in a cozy, book-lined study, wearing a comfortable knit sweater. The lighting should be soft and natural, as if coming from a nearby window." },
    { title: "Sophisticated Executive Portrait", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Generate a powerful and sophisticated portrait with the person in a stylish, tailored suit. The setting should be a minimalist, upscale interior with clean lines. The lighting should be studio-quality, creating a polished and refined look." },
    
    // Creative & Cinematic Portraits
    { title: "Cinematic Street Portrait", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop", prompt: "Transform this photo into a cinematic portrait with right pose and attire. The subject should be facing the camera. The setting should be a moody, rain-slicked city street at night, with neon lights reflecting in the background. The individual's expression should be contemplative." },
    { title: "Vintage 1970s Style", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Reimagine this image with a vintage, 1970s film photography aesthetic. The person should be dressed in retro-inspired clothing. The colors should be warm and slightly faded, with a soft grain effect." },
    { title: "Cyberpunk Future Portrait", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop", prompt: "Create a futuristic, cyberpunk-themed portrait. The subject should have subtle cybernetic enhancements and be set against a backdrop of a neon-drenched, technologically advanced cityscape. The subject should be facing the camera with right clothes and pose." },
    { title: "Fine Art Painterly Portrait", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop", prompt: "Generate a fine art portrait with a painterly quality. The background should be an abstract texture of deep blues and golds, and the lighting should be soft and diffused, creating a timeless and artistic feel." },
    
    // Outdoor & Nature Portraits
    { title: "Forest Sanctuary Portrait", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Recreate this photo as a portrait taken in a lush, green forest. The individual should be dressed in earthy tones, and the sunlight should be filtering through the trees, creating a serene and natural atmosphere." },
    { title: "Golden Hour Coastline", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Generate a portrait of the person on a dramatic, windswept coastline at golden hour. The lighting should be warm and golden, and their hair and clothing should appear to be gently blowing in the breeze." },
    { title: "Blooming Garden Portrait", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Transform this into a portrait set in a vibrant, blooming garden. The person should be surrounded by colorful flowers, and the lighting should be bright and cheerful, evoking a sense of joy." },
    { title: "Autumn Countryside Portrait", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Create a portrait of the individual in a rustic, countryside setting during autumn. They should be wearing warm, layered clothing, and the background should be filled with the rich colors of fall foliage." },
    { title: "Desert Minimalism", image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=400&h=500&fit=crop", prompt: "Reimagine this photo as if it were taken in a tranquil, minimalist desert landscape at dusk with right clothes and pose. The colors should be soft and muted, and the overall mood should be one of quiet contemplation." },
    
    // Lifestyle Portraits
    { title: "Urban Café Moment", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop", prompt: "Generate a candid-style portrait of the person enjoying a coffee in a chic, urban café. The focus should be on their relaxed expression, with the bustling café softly blurred in the background." },
    { title: "Street Style Fashion", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop", prompt: "Recreate this as a vibrant, street-style portrait in a bustling city. The person should be wearing fashionable, contemporary clothing and walking confidently down the street, with the dynamic energy of the city captured around them." },
    { title: "Artist in Studio", image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=500&fit=crop", prompt: "Turn this into a portrait of an artist in their creative studio. The background should be filled with canvases, paint, and brushes, and the individual should be dressed in comfortable, practical clothing with a few paint splatters." },
    { title: "Wanderlust Explorer", image: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=500&fit=crop", prompt: "Transform this photo into a portrait of a traveler exploring an old, European city. The background should feature charming, historic architecture, and the person's expression should convey a sense of wonder and adventure." },
    
    // Fantasy & Sci-Fi Portraits
    { title: "Fantasy Novel Character", image: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&h=500&fit=crop", prompt: "Reimagine this person as a character from a fantasy novel, with elegant, fantasy-inspired attire, set against a backdrop of an enchanted forest or ancient ruins." },
    { title: "Magical Ethereal Portrait", image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=500&fit=crop", prompt: "Create a whimsical portrait of the individual surrounded by glowing, magical particles in a dreamlike, ethereal setting. The colors should be soft and pastel." },
    { title: "Steampunk Victorian", image: "https://images.unsplash.com/photo-1506629905607-d9c297d3d45b?w=400&h=500&fit=crop", prompt: "Turn this into a portrait with a steampunk aesthetic. The individual should be wearing Victorian-era clothing with imaginative, steam-powered mechanical accessories, set in a workshop filled with gears and inventions." },
    { title: "Space Explorer Portrait", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop", prompt: "Generate a portrait of the person as a futuristic space explorer, looking out at a stunning, star-filled galaxy from the cockpit of a spaceship." },
    
    // Animation & Video Prompts
    { title: "Figurine Animation", image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop", prompt: "Two hands gently pick up the figure on the frame and rotate it slightly for inspection. The model in the packaging box remains stationary, while all other background elements stay unchanged." }
];